"""
Extract ankle positions, step events, and step length from pipeline 2D keypoints.

This script uses the HRNet/MotionAGFormer 2D keypoints generated by
``run_pipeline.py`` plus the tracking offsets generated in Step 1. It writes:

  - ankle_positions.csv: per-frame left/right ankle positions in original video coordinates
  - step_events.csv: detected foot-strike candidates and step length
  - optional overlay video with ankle/step markers

Distance calibration is optional. If no calibration is provided, step length is
reported in pixels. If homography points, start/end lines plus distance_m, or
--meters-per-pixel are provided, step length is also reported in meters.
"""

from __future__ import annotations

import argparse
import csv
import os
from pathlib import Path
from types import SimpleNamespace

import cv2
import numpy as np
import yaml
from scipy.signal import find_peaks, savgol_filter


RIGHT_ANKLE = 3
LEFT_ANKLE = 6
TEXT_COLOR = (0, 0, 0)

ANKLE_FIELDS = [
    "seq_frame", "offset_index", "orig_frame", "time_s", "seq_time_s", "cam",
    "right_ankle_x", "right_ankle_y", "right_ankle_conf",
    "left_ankle_x", "left_ankle_y", "left_ankle_conf",
    "lower_foot", "lower_ankle_x", "lower_ankle_y", "lower_ankle_conf",
]


def _load_keypoint_status_for(keypoints_npz_path):
    base = Path(keypoints_npz_path).parent
    for name in ("keypoint_status.npz", "newalgo_keypoint_status.npz"):
        path = base / name
        if path.exists():
            return np.load(path, allow_pickle=True), path
    return None, None


def _resolve_leg_mask_after_swaps(mask, swapped, left_idx, right_idx):
    resolved = mask.copy()
    if swapped is None or not np.any(swapped):
        return resolved
    resolved[np.ix_(swapped, [right_idx])] = mask[np.ix_(swapped, [left_idx])]
    resolved[np.ix_(swapped, [left_idx])] = mask[np.ix_(swapped, [right_idx])]
    return resolved


def _post_dp_fill_leg_gaps(recon, swapped, keypoints_npz_path,
                           conf_threshold=0.50,
                           hard_conf_threshold=0.20,
                           deviation_factor=2.0):
    """Fill leg bad points after DP has resolved left/right identity.

    DP decides which physical leg each left/right label represents. Knee/ankle
    low-confidence and outlier frames are therefore filled here, using the
    DP-resolved parent->joint trajectory, instead of before DP where the same
    label can still refer to the wrong physical leg.
    """
    status, status_path = _load_keypoint_status_for(keypoints_npz_path)
    if status is None:
        return None

    R_HIP, R_KNEE, R_ANKLE = 1, 2, 3
    L_HIP, L_KNEE, L_ANKLE = 4, 5, 6
    T = recon.shape[1]
    kp = recon[0, :, :, :2].astype(np.float64, copy=True)
    raw_conf = status["raw_confidence"][0].astype(np.float64)
    low_conf = status["low_conf_mask"][0].astype(bool)
    bilateral = status["bilateral_outlier_mask"][0].astype(bool)
    crossing = status["ankle_crossing_mask"][0].astype(bool)

    if swapped is None:
        swapped = np.zeros(T, dtype=bool)
    swapped = np.asarray(swapped, dtype=bool)

    raw_conf_resolved = raw_conf.copy()
    if np.any(swapped):
        for left_idx, right_idx in ((L_KNEE, R_KNEE), (L_ANKLE, R_ANKLE)):
            raw_conf_resolved[np.ix_(swapped, [right_idx])] = raw_conf[np.ix_(swapped, [left_idx])]
            raw_conf_resolved[np.ix_(swapped, [left_idx])] = raw_conf[np.ix_(swapped, [right_idx])]
    for left_idx, right_idx in ((L_KNEE, R_KNEE), (L_ANKLE, R_ANKLE)):
        low_conf = _resolve_leg_mask_after_swaps(low_conf, swapped, left_idx, right_idx)
        bilateral = _resolve_leg_mask_after_swaps(bilateral, swapped, left_idx, right_idx)
        crossing = _resolve_leg_mask_after_swaps(crossing, swapped, left_idx, right_idx)

    post_fill = np.zeros((T, recon.shape[2]), dtype=bool)
    all_idx = np.arange(T)
    thresholds = {
        R_KNEE: 8.0,
        L_KNEE: 8.0,
        R_ANKLE: 12.0,
        L_ANKLE: 12.0,
    }
    joint_specs = (
        (R_KNEE, R_HIP, False),
        (L_KNEE, L_HIP, False),
        (R_ANKLE, R_KNEE, True),
        (L_ANKLE, L_KNEE, True),
    )

    for joint_idx, parent_idx, use_crossing in joint_specs:
        base_bad = bilateral[:, joint_idx] | (raw_conf_resolved[:, joint_idx] < hard_conf_threshold)
        if use_crossing:
            base_bad = base_bad | crossing[:, joint_idx]
        moderate_low = (
            low_conf[:, joint_idx] &
            (raw_conf_resolved[:, joint_idx] >= hard_conf_threshold) &
            (raw_conf_resolved[:, joint_idx] < conf_threshold)
        )

        rel = kp[:, joint_idx] - kp[:, parent_idx]
        good_for_model = (
            (raw_conf_resolved[:, joint_idx] >= conf_threshold) &
            ~bilateral[:, joint_idx] &
            np.isfinite(rel).all(axis=1)
        )
        if use_crossing:
            good_for_model &= ~crossing[:, joint_idx]
        good_idx = np.flatnonzero(good_for_model)
        geometric_bad = np.zeros(T, dtype=bool)
        if good_idx.size >= 2 and np.any(moderate_low):
            interp_x = np.interp(all_idx, good_idx, rel[good_idx, 0])
            interp_y = np.interp(all_idx, good_idx, rel[good_idx, 1])
            deviation = np.hypot(rel[:, 0] - interp_x, rel[:, 1] - interp_y)
            geometric_bad = moderate_low & (deviation > thresholds[joint_idx] * deviation_factor)

        fill = base_bad | geometric_bad
        post_fill[:, joint_idx] = fill
        good_fill_idx = np.flatnonzero(~fill & np.isfinite(rel).all(axis=1))
        if good_fill_idx.size < 2 or not np.any(fill):
            continue

        fixed_rel_x = np.interp(all_idx, good_fill_idx, rel[good_fill_idx, 0])
        fixed_rel_y = np.interp(all_idx, good_fill_idx, rel[good_fill_idx, 1])
        kp[fill, joint_idx, 0] = kp[fill, parent_idx, 0] + fixed_rel_x[fill]
        kp[fill, joint_idx, 1] = kp[fill, parent_idx, 1] + fixed_rel_y[fill]

    recon[0, :, :, :2] = kp
    out_path = Path(keypoints_npz_path).parent / "post_dp_ankle_fill_mask.npz"
    np.savez_compressed(
        out_path,
        post_dp_leg_fill_mask=post_fill,
        post_dp_ankle_fill_mask=post_fill,
        dp_leg_swapped=swapped,
        source_status_path=str(status_path),
    )
    return post_fill


def _post_dp_smooth_and_limit_legs(recon, sg_polyorder=2, bone_blend=0.8):
    """Smooth and constrain leg geometry after DP has resolved L/R identity."""
    leg_joints = (1, 2, 3, 4, 5, 6)
    sg_windows = {
        1: 11,  # RHip
        2: 7,   # RKnee
        3: 3,   # RAnkle
        4: 11,  # LHip
        5: 7,   # LKnee
        6: 3,   # LAnkle
    }
    leg_bones = ((1, 2), (2, 3), (4, 5), (5, 6))
    knee_limits = ((1, 2, 3, 20.0), (4, 5, 6, 20.0))

    M, T, J, _ = recon.shape
    kp = recon[:, :, :, :2].astype(np.float64, copy=True)

    for person_idx in range(M):
        for joint_idx in leg_joints:
            win = min(int(sg_windows[joint_idx]), T)
            if win % 2 == 0:
                win -= 1
            if win >= sg_polyorder + 2 and T >= win:
                kp[person_idx, :, joint_idx, 0] = savgol_filter(
                    kp[person_idx, :, joint_idx, 0],
                    win,
                    sg_polyorder,
                    mode="mirror",
                )
                kp[person_idx, :, joint_idx, 1] = savgol_filter(
                    kp[person_idx, :, joint_idx, 1],
                    win,
                    sg_polyorder,
                    mode="mirror",
                )

        for parent_idx, child_idx in leg_bones:
            diff = kp[person_idx, :, child_idx] - kp[person_idx, :, parent_idx]
            lengths = np.linalg.norm(diff, axis=1)
            valid = lengths > 1.0
            if valid.sum() < 2:
                continue
            ref_len = float(np.median(lengths[valid]))
            ratios = np.where(lengths > 1.0, ref_len / lengths, 1.0)
            adjust = np.abs(ratios - 1.0) > 0.10
            if not np.any(adjust):
                continue
            normalized = kp[person_idx, :, parent_idx] + diff * ratios[:, None]
            kp[person_idx, adjust, child_idx] = (
                (1.0 - bone_blend) * kp[person_idx, adjust, child_idx]
                + bone_blend * normalized[adjust]
            )

        for p_idx, j_idx, d_idx, min_deg in knee_limits:
            p = kp[person_idx, :, p_idx]
            j = kp[person_idx, :, j_idx]
            d = kp[person_idx, :, d_idx]
            v1 = p - j
            v2 = d - j
            len1 = np.linalg.norm(v1, axis=1)
            len2 = np.linalg.norm(v2, axis=1)
            valid = (len1 > 1.0) & (len2 > 1.0)
            cos_a = np.einsum("ti,ti->t", v1, v2) / np.maximum(len1 * len2, 1e-8)
            angles = np.degrees(np.arccos(np.clip(cos_a, -1.0, 1.0)))
            needs_fix = valid & (angles < min_deg)
            for t in np.where(needs_fix)[0]:
                delta = np.radians(float(min_deg) - float(angles[t]))
                cross = v1[t, 0] * v2[t, 1] - v1[t, 1] * v2[t, 0]
                if cross < 0:
                    delta = -delta
                cos_d, sin_d = np.cos(delta), np.sin(delta)
                v2r = np.array([
                    v2[t, 0] * cos_d - v2[t, 1] * sin_d,
                    v2[t, 0] * sin_d + v2[t, 1] * cos_d,
                ])
                kp[person_idx, t, d_idx] = j[t] + v2r

    recon[:, :, :, :2] = kp
    return recon

STEP_FIELDS = [
    "step_index", "seq_frame", "orig_frame", "time_s", "seq_time_s", "cam", "foot",
    "ankle_x", "ankle_y", "ankle_conf",
    "track_position_px", "world_x_m", "world_y_m",
    "step_length_px", "step_length_m",
    "cadence_spm", "avg_cadence_spm",
]



def _parse_line(values):
    if values is None:
        return None
    if len(values) != 4:
        raise ValueError("line must be x1,y1,x2,y2")
    return [(float(values[0]), float(values[1])), (float(values[2]), float(values[3]))]


def _midpoint(line):
    return ((line[0][0] + line[1][0]) / 2.0, (line[0][1] + line[1][1]) / 2.0)


def _track_calibration(start_line, end_line, distance_m, meters_per_pixel):
    if start_line and end_line and distance_m:
        start_mid = _midpoint(start_line)
        end_mid = _midpoint(end_line)
        dx = end_mid[0] - start_mid[0]
        dy = end_mid[1] - start_mid[1]
        span = float((dx * dx + dy * dy) ** 0.5)
        if span <= 0:
            raise ValueError("start_line and end_line have zero distance")
        return {
            "mode": "line",
            "origin": start_mid,
            "direction": (dx / span, dy / span),
            "meters_per_pixel": float(distance_m) / span,
            "homography": None,
        }

    if meters_per_pixel:
        return {
            "mode": "scale",
            "origin": (0.0, 0.0),
            "direction": (1.0, 0.0),
            "meters_per_pixel": float(meters_per_pixel),
            "homography": None,
        }

    return {
        "mode": "pixel",
        "origin": (0.0, 0.0),
        "direction": (1.0, 0.0),
        "meters_per_pixel": None,
        "homography": None,
    }


def _homography_calibration(src_points, dst_points_world):
    if not src_points or not dst_points_world:
        return None

    src = np.asarray(src_points, dtype=np.float32)
    dst = np.asarray(dst_points_world, dtype=np.float32)
    if src.shape != dst.shape or src.ndim != 2 or src.shape[1] != 2:
        raise ValueError("homography_src_points / homography_dst_world must both be shape (N, 2)")
    if len(src) < 4:
        raise ValueError("homography needs at least 4 point pairs")

    H, _ = cv2.findHomography(src, dst, cv2.RANSAC, 5.0)
    if H is None:
        raise ValueError("homography calculation failed")

    return {
        "mode": "homography",
        "origin": (0.0, 0.0),
        "direction": (1.0, 0.0),
        "meters_per_pixel": None,
        "homography": H,
        "world_x_min": float(np.nanmin(dst[:, 0])),
        "world_x_max": float(np.nanmax(dst[:, 0])),
    }


def _make_calibration(cam_cfg, cfg, args, start_line, end_line, distance_m):
    calibration = _track_calibration(
        start_line=start_line,
        end_line=end_line,
        distance_m=distance_m,
        meters_per_pixel=args.meters_per_pixel,
    )
    if calibration.get("meters_per_pixel") is not None:
        return calibration

    homography = _homography_calibration(
        cam_cfg.get("homography_src_points") or cfg.get("homography_src_points"),
        cam_cfg.get("homography_dst_world") or cfg.get("homography_dst_world"),
    )
    if homography is not None:
        return homography

    return calibration


def _transform_homography(point, H):
    pts = np.array([[[float(point[0]), float(point[1])]]], dtype=np.float32)
    mapped = cv2.perspectiveTransform(pts, H)
    return float(mapped[0, 0, 0]), float(mapped[0, 0, 1])


def _project(point, calibration):
    if calibration.get("mode") == "homography":
        world_x, _ = _transform_homography(point, calibration["homography"])
        return world_x

    ox, oy = calibration["origin"]
    ux, uy = calibration["direction"]
    return (float(point[0]) - ox) * ux + (float(point[1]) - oy) * uy


def _default_paths_from_config(config_path):
    with open(config_path, "r", encoding="utf-8") as f:
        cfg = yaml.safe_load(f)

    cameras = cfg.get("cameras") or []
    if not cameras:
        raise ValueError("config has no cameras")

    cam = cameras[0]
    video_path = cam.get("video_path")
    if not video_path:
        raise ValueError("first camera has no video_path")

    output_dir = cfg.get("output_dir") or str(Path(video_path).resolve().parent)
    stem = Path(video_path).stem
    tracked_stem = f"{stem}_tracked"

    return {
        "config": cfg,
        "camera": cam,
        "video": video_path,
        "output_dir": output_dir,
        "keypoints_npz": str(Path(output_dir) / tracked_stem / "input_2D" / "keypoints.npz"),
        "offsets_npz": str(Path(output_dir) / f"{stem}_offsets.npz"),
    }


def load_ankle_positions(keypoints_npz, offsets_npz, fps):
    kps_data = np.load(keypoints_npz, allow_pickle=True)
    offsets_data = np.load(offsets_npz, allow_pickle=True)

    keypoints = kps_data["reconstruction"][0]
    valid_frames = np.asarray(kps_data["valid_frames"]).flatten().astype(int)
    offsets = offsets_data["offsets"]
    orig_frames = offsets_data["orig_frames"]
    cam_indices = (
        offsets_data["cam_indices"].astype(int)
        if "cam_indices" in offsets_data
        else np.zeros(len(orig_frames), dtype=int)
    )

    rows = []
    for i, offset_idx in enumerate(valid_frames):
        if offset_idx >= len(offsets) or i >= len(keypoints):
            continue

        frame_kps = keypoints[i]
        off_x, off_y = offsets[offset_idx]
        right = frame_kps[RIGHT_ANKLE]
        left = frame_kps[LEFT_ANKLE]

        right_x, right_y = float(right[0] + off_x), float(right[1] + off_y)
        left_x, left_y = float(left[0] + off_x), float(left[1] + off_y)
        right_conf = float(right[2]) if len(right) > 2 else np.nan
        left_conf = float(left[2]) if len(left) > 2 else np.nan

        if right_y >= left_y:
            lower_foot = "right"
            lower_x, lower_y, lower_conf = right_x, right_y, right_conf
        else:
            lower_foot = "left"
            lower_x, lower_y, lower_conf = left_x, left_y, left_conf

        orig_frame = int(orig_frames[offset_idx])
        rows.append({
            "seq_frame": int(i),
            "offset_index": int(offset_idx),
            "orig_frame": orig_frame,
            "time_s": orig_frame / fps if fps > 0 else i / 60.0,
            "seq_time_s": i / fps if fps > 0 else i / 60.0,
            "cam": int(cam_indices[offset_idx]),
            "right_ankle_x": right_x,
            "right_ankle_y": right_y,
            "right_ankle_conf": right_conf,
            "left_ankle_x": left_x,
            "left_ankle_y": left_y,
            "left_ankle_conf": left_conf,
            "lower_foot": lower_foot,
            "lower_ankle_x": lower_x,
            "lower_ankle_y": lower_y,
            "lower_ankle_conf": lower_conf,
        })
    return rows


def detect_steps(ankle_rows, calibration, fps=None, min_step_frames=None, prominence=None):
    if not ankle_rows:
        return []

    # Estimate FPS from ankle_rows timestamps if not provided.
    if fps is None and len(ankle_rows) >= 2:
        t0 = float(ankle_rows[0]['seq_time_s'])
        t1 = float(ankle_rows[-1]['seq_time_s'])
        n  = len(ankle_rows)
        fps = (n - 1) / (t1 - t0) if t1 > t0 else 30.0
    fps = fps or 30.0

    if min_step_frames is None:
        # Minimum frames between consecutive touchdowns based on fps.
        # Assumes max cadence ~4.5 steps/s per foot (270 spm).
        min_step_frames = max(4, int(fps / 4.5))
    min_touchdown_gap_frames = max(3, min_step_frames // 2)

    def smooth(values):
        from scipy.signal import butter, filtfilt
        n = len(values)
        if n < 13:
            return values
        # Low-pass Butterworth at 6 Hz removes skeleton jitter while preserving
        # step peaks (~2-4 Hz). Used only for peak detection; reported ankle
        # coordinates always come from the original rows.
        cutoff_hz = 6.0
        nyq = fps / 2.0
        if cutoff_hz >= nyq:
            return values
        b, a = butter(4, cutoff_hz / nyq, btype='low')
        return filtfilt(b, a, values)

    # Use combined lower_ankle_y signal so detection is robust to left/right label swaps.
    # distance = fps/8 (~7 at 60fps) allows alternating-foot peaks spaced ~fps/cadence/2
    # frames apart to both be detected, unlike min_step_frames which is calibrated for
    # same-foot intervals and would suppress every other step.
    y = np.array([r["lower_ankle_y"] for r in ankle_rows], dtype=float)
    y_smooth = smooth(y)
    lower_prominence = prominence
    if lower_prominence is None:
        q75, q25 = np.nanpercentile(y_smooth, [75, 25])
        lower_prominence = max((q75 - q25) * 0.20, 1.5)

    peak_distance = max(3, int(fps / 8.0))
    peaks, props = find_peaks(
        y_smooth,
        distance=peak_distance,
        prominence=lower_prominence,
    )
    prominences = props.get("prominences", np.zeros(len(peaks), dtype=float))

    def _valid_conf(conf, min_conf):
        try:
            value = float(conf)
        except (TypeError, ValueError):
            return False
        return np.isnan(value) or value >= min_conf

    def _inside_calibrated_range(candidate):
        if calibration.get("mode") != "homography":
            return True
        world_x = _project((candidate["ankle_x"], candidate["ankle_y"]), calibration)
        x_min = calibration.get("world_x_min")
        x_max = calibration.get("world_x_max")
        if x_min is None or x_max is None:
            return True
        margin_m = 0.5
        return float(x_min) - margin_m <= world_x <= float(x_max) + margin_m

    def _candidate_from_peak(peak_idx, peak_prominence, source):
        row = ankle_rows[int(peak_idx)]
        conf = row["lower_ankle_conf"]
        if not _valid_conf(conf, 0.30):
            return None
        # Foot label: whichever ankle is lower at this frame (lower_foot is pre-computed).
        candidate = {
            "row_idx": int(peak_idx),
            "row": row,
            "foot": row["lower_foot"],
            "ankle_x": row["lower_ankle_x"],
            "ankle_y": row["lower_ankle_y"],
            "ankle_conf": conf,
            "prominence": float(peak_prominence),
            "source": source,
        }
        return candidate if _inside_calibrated_range(candidate) else None

    candidates = []
    for peak_idx, peak_prominence in zip(peaks, prominences):
        candidate = _candidate_from_peak(peak_idx, peak_prominence, "smooth")
        if candidate is not None:
            candidates.append(candidate)

    filtered_candidates = []
    for candidate in candidates:
        if not filtered_candidates:
            filtered_candidates.append(candidate)
            continue

        previous = filtered_candidates[-1]
        frame_gap = int(candidate["row"]["seq_frame"]) - int(previous["row"]["seq_frame"])
        if frame_gap < min_touchdown_gap_frames:
            prev_score = (previous["prominence"], previous["ankle_conf"], previous["ankle_y"])
            cand_score = (candidate["prominence"], candidate["ankle_conf"], candidate["ankle_y"])
            if cand_score > prev_score:
                filtered_candidates[-1] = candidate
        else:
            filtered_candidates.append(candidate)

    # Rescue narrow raw peaks that the low-pass filter may suppress.
    # This is intentionally conservative: raw peaks are only considered inside
    # unusually large time gaps or unusually large track-position gaps between
    # smooth detections, and still must pass confidence, prominence, timing,
    # and track-position checks.
    raw_q75, raw_q25 = np.nanpercentile(y, [75, 25])
    raw_prominence = max((raw_q75 - raw_q25) * 0.20, 1.5)
    raw_peaks, raw_props = find_peaks(
        y,
        distance=peak_distance,
        prominence=raw_prominence,
    )
    raw_prominences = {
        int(peak): float(prom)
        for peak, prom in zip(raw_peaks, raw_props.get("prominences", []))
    }
    smooth_peak_indexes = {c["row_idx"] for c in filtered_candidates}
    rescue_gap_frames = max(min_step_frames + peak_distance, int(round(min_step_frames * 1.8)))
    rescued_candidates = []

    def _track_pos(candidate):
        return _project((candidate["ankle_x"], candidate["ankle_y"]), calibration)

    def _large_step_rescue_threshold(candidates):
        if len(candidates) < 3:
            return None

        positions = [_track_pos(candidate) for candidate in candidates]
        step_lengths = [
            abs(positions[i] - positions[i - 1])
            for i in range(1, len(positions))
        ]
        typical_step = float(np.nanmedian(step_lengths)) if step_lengths else 0.0
        thresholds = []
        if typical_step > 1e-6:
            thresholds.append(typical_step * 1.6)

        # If calibration is available, also treat implausibly long human steps
        # as a signal that an intermediate touchdown may have been missed.
        large_step_m = 2.46
        if calibration.get("mode") == "homography":
            thresholds.append(large_step_m)
        else:
            meters_per_pixel = calibration.get("meters_per_pixel")
            if meters_per_pixel:
                thresholds.append(large_step_m / float(meters_per_pixel))

        return min(thresholds) if thresholds else None

    def _position_is_between(prev_candidate, rescue_candidate, next_candidate):
        prev_pos = _track_pos(prev_candidate)
        next_pos = _track_pos(next_candidate)
        rescue_pos = _track_pos(rescue_candidate)
        span = abs(next_pos - prev_pos)
        if span <= 1e-6:
            return True
        min_margin = 0.20 if calibration.get("mode") == "homography" else 20.0
        margin = max(min_margin, span * 0.25)
        return min(prev_pos, next_pos) - margin <= rescue_pos <= max(prev_pos, next_pos) + margin

    def _rescue_height_is_plausible(prev_candidate, rescue_candidate, next_candidate):
        # A raw rescue peak should be near the landing height of the surrounding
        # contacts. Peaks much higher in the image are usually ankle jitter,
        # even if they are local maxima in the raw signal.
        surrounding_y = min(float(prev_candidate["ankle_y"]), float(next_candidate["ankle_y"]))
        return float(rescue_candidate["ankle_y"]) >= surrounding_y - raw_prominence

    def _rescue_split_is_plausible(prev_candidate, rescue_candidate, next_candidate):
        prev_pos = _track_pos(prev_candidate)
        next_pos = _track_pos(next_candidate)
        rescue_pos = _track_pos(rescue_candidate)
        span = abs(next_pos - prev_pos)
        if span <= 1e-6:
            return True
        before = abs(rescue_pos - prev_pos)
        after = abs(next_pos - rescue_pos)
        return min(before, after) >= span * 0.25

    large_step_rescue_threshold = _large_step_rescue_threshold(filtered_candidates)

    for prev_candidate, next_candidate in zip(filtered_candidates, filtered_candidates[1:]):
        rescued_candidates.append(prev_candidate)
        gap = int(next_candidate["row"]["seq_frame"]) - int(prev_candidate["row"]["seq_frame"])
        movement = abs(_track_pos(next_candidate) - _track_pos(prev_candidate))
        large_step_gap = (
            large_step_rescue_threshold is not None
            and movement > large_step_rescue_threshold
        )
        if gap < rescue_gap_frames and not large_step_gap:
            continue

        prev_idx = prev_candidate["row_idx"]
        next_idx = next_candidate["row_idx"]
        middle_raw_candidates = []
        for peak_idx in raw_peaks:
            peak_idx = int(peak_idx)
            if peak_idx in smooth_peak_indexes:
                continue
            if not (prev_idx < peak_idx < next_idx):
                continue
            if peak_idx - prev_idx < min_touchdown_gap_frames:
                continue
            if next_idx - peak_idx < min_touchdown_gap_frames:
                continue

            candidate = _candidate_from_peak(
                peak_idx,
                raw_prominences.get(peak_idx, 0.0),
                "raw_rescue",
            )
            if candidate is None:
                continue
            if not _valid_conf(candidate["ankle_conf"], 0.50):
                continue
            if candidate["prominence"] < raw_prominence:
                continue
            if not _position_is_between(prev_candidate, candidate, next_candidate):
                continue
            if not _rescue_height_is_plausible(prev_candidate, candidate, next_candidate):
                continue
            if not _rescue_split_is_plausible(prev_candidate, candidate, next_candidate):
                continue
            middle_raw_candidates.append(candidate)

        if middle_raw_candidates:
            middle_raw_candidates.sort(
                key=lambda c: (c["prominence"], c["ankle_conf"], c["ankle_y"]),
                reverse=True,
            )
            rescued_candidates.append(middle_raw_candidates[0])

    if filtered_candidates:
        rescued_candidates.append(filtered_candidates[-1])
    filtered_candidates = sorted(rescued_candidates, key=lambda c: c["row_idx"])

    def _candidate_score(candidate):
        return (candidate["prominence"], candidate["ankle_conf"], candidate["ankle_y"])

    def _min_valid_step_track_units():
        # Normal running step length is usually well above 0.6 m. Values below
        # this are more likely duplicate contacts from ankle jitter than true
        # alternating touchdowns. Keep this conservative for short runners or
        # slow jogs.
        min_step_length_m = 0.60
        if calibration.get("mode") == "homography":
            return min_step_length_m

        meters_per_pixel = calibration.get("meters_per_pixel")
        if meters_per_pixel:
            return min_step_length_m / float(meters_per_pixel)

        return None

    def _dedupe_short_contacts(candidates):
        if len(candidates) < 2:
            return candidates

        positions = [_track_pos(candidate) for candidate in candidates]
        step_lengths = [
            abs(positions[i] - positions[i - 1])
            for i in range(1, len(positions))
        ]
        typical_step_px = float(np.nanmedian(step_lengths)) if step_lengths else 0.0
        absolute_short_step = _min_valid_step_track_units()
        if absolute_short_step is not None:
            short_step_px = max(absolute_short_step, typical_step_px * 0.35)
        else:
            short_step_px = max(20.0, typical_step_px * 0.35)
        short_gap_frames = max(min_touchdown_gap_frames, int(round(fps / 5.0)))

        deduped = []
        for candidate in candidates:
            if not deduped:
                deduped.append(candidate)
                continue

            previous = deduped[-1]
            gap = int(candidate["row"]["seq_frame"]) - int(previous["row"]["seq_frame"])
            movement = abs(_track_pos(candidate) - _track_pos(previous))
            duplicate = (
                (movement < short_step_px) or
                (gap < short_gap_frames and movement < short_step_px)
            )
            if duplicate:
                if _candidate_score(candidate) > _candidate_score(previous):
                    deduped[-1] = candidate
            else:
                deduped.append(candidate)
        return deduped

    filtered_candidates = _dedupe_short_contacts(filtered_candidates)

    def _apply_alternating_foot_labels(candidates):
        # 跑步必定左右交替落地。逐幀計算的 lower_foot 只在單一幀比較左右腳踝
        # y 座標，容易被雜訊誤判，因此只信任它來決定「第一步」（用峰值附近一
        # 個小視窗做多數決，降低錨點本身判斷錯誤的機率）。第二步以後一律直接
        # 取前一步的相反腳，不再重新讀取 lower_foot。落地時間點與
        # ankle_x/ankle_y（實際偵測到的踝關節位置）完全不變，只修正 foot 這個標籤欄位。
        if not candidates:
            return candidates

        anchor_window_radius = max(1, peak_distance // 3)
        anchor_row_idx = candidates[0]["row_idx"]
        lo = max(0, anchor_row_idx - anchor_window_radius)
        hi = min(len(ankle_rows) - 1, anchor_row_idx + anchor_window_radius)
        votes = [ankle_rows[i]["lower_foot"] for i in range(lo, hi + 1)]
        left_votes = votes.count("left")
        right_votes = votes.count("right")
        if left_votes > right_votes:
            anchor_foot = "left"
        elif right_votes > left_votes:
            anchor_foot = "right"
        else:
            anchor_foot = candidates[0]["foot"]  # tie: 保留原本單幀判斷值

        candidates[0]["foot"] = anchor_foot
        for i in range(1, len(candidates)):
            candidates[i]["foot"] = "left" if candidates[i - 1]["foot"] == "right" else "right"
        return candidates

    filtered_candidates = _apply_alternating_foot_labels(filtered_candidates)

    events = []
    prev_proj = None
    for step_idx, candidate in enumerate(filtered_candidates, start=1):
        row = candidate["row"]
        point = (candidate["ankle_x"], candidate["ankle_y"])
        track_pos = _project(point, calibration)
        world_x = world_y = None
        if calibration.get("mode") == "homography":
            world_x, world_y = _transform_homography(point, calibration["homography"])
            step_len_px = None
            step_len_m = None if prev_proj is None else abs(track_pos - prev_proj)
        else:
            step_len_px = None if prev_proj is None else abs(track_pos - prev_proj)
            mpp = calibration["meters_per_pixel"]
            step_len_m = None if step_len_px is None or mpp is None else step_len_px * mpp
        prev_proj = track_pos

        events.append({
            "step_index": step_idx,
            "seq_frame": row["seq_frame"],
            "orig_frame": row["orig_frame"],
            "time_s": row["time_s"],
            "seq_time_s": row["seq_time_s"],
            "cam": row["cam"],
            "foot": candidate["foot"],
            "ankle_x": candidate["ankle_x"],
            "ankle_y": candidate["ankle_y"],
            "ankle_conf": candidate["ankle_conf"],
            "track_position_px": None if calibration.get("mode") == "homography" else track_pos,
            "world_x_m": world_x,
            "world_y_m": world_y,
            "step_length_px": step_len_px,
            "step_length_m": step_len_m,
        })

    return events


def add_cadence(step_events):
    """Add instantaneous and summary cadence in steps per minute."""
    if not step_events:
        return None

    prev_time = None
    intervals = []
    for event in step_events:
        cadence = None
        current_time = float(event["time_s"])
        if prev_time is not None:
            dt = current_time - prev_time
            if dt > 0:
                cadence = 60.0 / dt
                intervals.append(dt)
        event["cadence_spm"] = cadence
        prev_time = current_time

    if len(step_events) >= 2:
        elapsed = float(step_events[-1]["time_s"]) - float(step_events[0]["time_s"])
        if elapsed > 0:
            summary = (len(step_events) - 1) / elapsed * 60.0
        else:
            summary = None
    else:
        summary = None

    for event in step_events:
        event["avg_cadence_spm"] = summary
    return summary


def add_global_cadence(step_events, ankle_rows):
    """Add one full-video average cadence in steps per minute."""
    if not step_events or not ankle_rows:
        return None

    rows_sorted = sorted(ankle_rows, key=lambda row: int(row["seq_frame"]))
    duration = float(rows_sorted[-1]["seq_time_s"]) - float(rows_sorted[0]["seq_time_s"])
    summary = (len(step_events) / duration * 60.0) if duration > 0 else None

    prev_time = None
    for event in sorted(step_events, key=lambda item: int(item["seq_frame"])):
        cadence = None
        current_time = float(event["seq_time_s"])
        if prev_time is not None:
            dt = current_time - prev_time
            if dt > 0:
                cadence = 60.0 / dt
        event["cadence_spm"] = cadence
        event["avg_cadence_spm"] = summary
        prev_time = current_time

    return summary


def apply_anchor_leg_correction(keypoints_npz_path, step_events):
    """Refine 2D keypoint L/R leg identity using confirmed touchdown events.

    step_events (from detect_steps(), already guaranteed to alternate feet)
    are used as ground-truth anchors: at each touchdown's seq_frame, the
    stance (lower) ankle is known to be left or right. Between two
    consecutive anchors, leg identity is propagated frame-to-frame by
    least-movement continuity (only two legs to disambiguate, bounded by
    hard truth on both ends) -- this only refines segments that already
    have two anchors on both sides; frames before the first anchor or
    after the last keep whatever identity the pose-estimation stage
    already assigned (e.g. via cost-based correction).

    Overwrites keypoints_npz_path in place with the refined array and returns
    a boolean mask where True means that frame's left/right leg identity was
    swapped. If fewer than 2 step_events exist, returns None (not enough
    anchors to refine).
    """
    if len(step_events) < 2:
        return None

    L_HIP, L_KNEE, L_ANKLE = 4, 5, 6
    R_HIP, R_KNEE, R_ANKLE = 1, 2, 3
    LEG_L, LEG_R = [L_HIP, L_KNEE, L_ANKLE], [R_HIP, R_KNEE, R_ANKLE]
    vector_weight = 1.0
    coord_weight = 0.20
    switch_penalty = 8.0
    stance_penalty = 90.0
    anchor_penalty = 1000.0
    velocity_weight = 1.0
    y_weight = 0.25
    knee_angle_weight = 0.4
    velocity_margin = 3.0
    knee_angle_margin = 15.0
    early_switch_until = 0.65
    early_switch_weight = 50.0

    data = np.load(keypoints_npz_path, allow_pickle=True)
    recon = data["reconstruction"]  # (M, T, J, C) -- C includes x, y, conf
    valid_frames = data["valid_frames"]

    kp = recon[0, :, :, :2].astype(np.float64)
    result = kp.copy()

    T = kp.shape[0]
    ankle_vel = {"right": np.zeros(T), "left": np.zeros(T)}
    for t in range(1, T):
        ankle_vel["right"][t] = np.linalg.norm(kp[t, R_ANKLE] - kp[t - 1, R_ANKLE])
        ankle_vel["left"][t] = np.linalg.norm(kp[t, L_ANKLE] - kp[t - 1, L_ANKLE])
    for foot in ("right", "left"):
        padded = np.pad(ankle_vel[foot], (1, 1), mode="edge")
        ankle_vel[foot] = np.asarray([
            np.median(padded[t:t + 3]) for t in range(T)
        ], dtype=np.float64)

    def _estimate_seq_fps(events):
        samples = []
        sorted_events = sorted(events, key=lambda item: int(item["seq_frame"]))
        for a, b in zip(sorted_events, sorted_events[1:]):
            frame_delta = int(b["seq_frame"]) - int(a["seq_frame"])
            if frame_delta <= 0:
                continue
            for time_key in ("seq_time_s", "time_s"):
                if a.get(time_key) is None or b.get(time_key) is None:
                    continue
                try:
                    time_delta = float(b[time_key]) - float(a[time_key])
                except (TypeError, ValueError):
                    continue
                if time_delta > 1e-6:
                    samples.append(frame_delta / time_delta)
                    break
        if not samples:
            return 60.0
        fps = float(np.median(samples))
        if not np.isfinite(fps) or fps <= 0:
            return 60.0
        return fps

    seq_fps = _estimate_seq_fps(step_events)

    def _clamp(value, lower, upper):
        return max(lower, min(upper, value))

    def _other(foot):
        return "left" if foot == "right" else "right"

    def _stance_extent(anchor_t, other_end_t, foot):
        # The stance influence range must not depend on the pre-DP left/right
        # labels, because those labels are exactly what DP is trying to resolve.
        # Use a fixed fraction of the adjacent touchdown gap, with FPS-scaled
        # min/max guards so the same seconds are covered at 30/60/120 fps.
        step = 1 if other_end_t > anchor_t else -1
        gap = abs(int(other_end_t) - int(anchor_t))
        if gap <= 1:
            return anchor_t

        if step > 0:
            raw_window = int(round(gap * 0.35))
            min_window = max(1, int(round(seq_fps * 0.04)))
            max_window = max(min_window, int(round(seq_fps * 0.12)))
        else:
            raw_window = int(round(gap * 0.20))
            min_window = max(1, int(round(seq_fps * 0.02)))
            max_window = max(min_window, int(round(seq_fps * 0.07)))

        window = _clamp(raw_window, min_window, max_window)
        window = min(window, gap - 1)
        return anchor_t + step * window

    def _legs_for_state(t, state):
        if state:
            return kp[t, LEG_L], kp[t, LEG_R]
        return kp[t, LEG_R], kp[t, LEG_L]

    def _leg_vectors(right_leg, left_leg):
        return np.asarray([
            right_leg[1] - right_leg[0],
            right_leg[2] - right_leg[0],
            left_leg[1] - left_leg[0],
            left_leg[2] - left_leg[0],
        ], dtype=np.float64)

    def _knee_angle(leg):
        v1 = leg[0] - leg[1]
        v2 = leg[2] - leg[1]
        denom = np.linalg.norm(v1) * np.linalg.norm(v2)
        if denom < 1e-8:
            return 0.0
        cos_a = np.dot(v1, v2) / denom
        return float(np.degrees(np.arccos(np.clip(cos_a, -1.0, 1.0))))

    def _transition_cost(prev_t, prev_state, t, state):
        prev_r, prev_l = _legs_for_state(prev_t, prev_state)
        cur_r, cur_l = _legs_for_state(t, state)
        vector_cost = np.linalg.norm(
            _leg_vectors(cur_r, cur_l) - _leg_vectors(prev_r, prev_l),
            axis=1,
        ).sum()
        coord_cost = (
            np.linalg.norm(cur_r - prev_r, axis=1).sum() +
            np.linalg.norm(cur_l - prev_l, axis=1).sum()
        )
        cost = vector_weight * vector_cost + coord_weight * coord_cost
        if state != prev_state:
            cost += switch_penalty
        return cost

    def _lower_foot_for_state(t, state):
        right_leg, left_leg = _legs_for_state(t, state)
        return "right" if right_leg[2, 1] >= left_leg[2, 1] else "left"

    def _foot_mismatch_penalty(t, state, expected_foot, penalty):
        if _lower_foot_for_state(t, state) == expected_foot:
            return 0.0
        right_leg, left_leg = _legs_for_state(t, state)
        if expected_foot == "right":
            y_gap = max(0.0, float(left_leg[2, 1] - right_leg[2, 1]))
        else:
            y_gap = max(0.0, float(right_leg[2, 1] - left_leg[2, 1]))
        return penalty + y_gap

    def _stance_evidence_cost(t, state, expected_foot, penalty):
        right_leg, left_leg = _legs_for_state(t, state)
        if expected_foot == "right":
            stance_leg, swing_leg = right_leg, left_leg
            stance_vel = ankle_vel["right"][t] if not state else ankle_vel["left"][t]
            swing_vel = ankle_vel["left"][t] if not state else ankle_vel["right"][t]
        else:
            stance_leg, swing_leg = left_leg, right_leg
            stance_vel = ankle_vel["left"][t] if not state else ankle_vel["right"][t]
            swing_vel = ankle_vel["right"][t] if not state else ankle_vel["left"][t]

        velocity_cost = max(0.0, velocity_margin - float(swing_vel - stance_vel))
        y_cost = max(0.0, float(swing_leg[2, 1] - stance_leg[2, 1]))
        angle_gap = _knee_angle(stance_leg) - _knee_angle(swing_leg)
        angle_cost = max(0.0, knee_angle_margin - angle_gap)
        return penalty + (
            velocity_weight * velocity_cost +
            y_weight * y_cost +
            knee_angle_weight * angle_cost
        )

    def _observation_cost(t, state, t_a, foot_a, t_b, foot_b, post_end, pre_start):
        if t == t_a:
            return _foot_mismatch_penalty(t, state, foot_a, anchor_penalty)
        if t == t_b:
            return _foot_mismatch_penalty(t, state, foot_b, anchor_penalty)

        near_start = t <= post_end
        near_end = t >= pre_start
        if near_start and near_end:
            expected = foot_a if (t - t_a) <= (t_b - t) else foot_b
            return _stance_evidence_cost(t, state, expected, stance_penalty)
        if near_start:
            return _stance_evidence_cost(t, state, foot_a, stance_penalty)
        if near_end:
            return _stance_evidence_cost(t, state, foot_b, stance_penalty)
        return 0.0

    def _switch_timing_cost(t_a, t_b, t, prev_state, state):
        if state == prev_state:
            return 0.0
        span = max(1, t_b - t_a)
        progress = (t - t_a) / span
        if progress >= early_switch_until:
            return 0.0
        return (early_switch_until - progress) * early_switch_weight

    def _solve_segment_states(t_a, foot_a, t_b, foot_b):
        post_end = _stance_extent(t_a, t_b, foot_a)
        pre_start = _stance_extent(t_b, t_a, foot_b)

        frames = list(range(t_a, t_b + 1))
        dp = np.full((len(frames), 2), np.inf, dtype=np.float64)
        parent = np.full((len(frames), 2), -1, dtype=np.int8)

        for state in (0, 1):
            dp[0, state] = _observation_cost(t_a, state, t_a, foot_a, t_b, foot_b, post_end, pre_start)

        for idx in range(1, len(frames)):
            t = frames[idx]
            prev_t = frames[idx - 1]
            for state in (0, 1):
                obs = _observation_cost(t, state, t_a, foot_a, t_b, foot_b, post_end, pre_start)
                best_cost = np.inf
                best_prev = 0
                for prev_state in (0, 1):
                    cost = (
                        dp[idx - 1, prev_state] +
                        _transition_cost(prev_t, prev_state, t, state) +
                        obs +
                        _switch_timing_cost(t_a, t_b, t, prev_state, state)
                    )
                    if cost < best_cost:
                        best_cost = cost
                        best_prev = prev_state
                dp[idx, state] = best_cost
                parent[idx, state] = best_prev

        states = {}
        state = int(np.argmin(dp[-1]))
        for idx in range(len(frames) - 1, -1, -1):
            states[frames[idx]] = state
            state = int(parent[idx, state]) if idx > 0 else state

        return states

    swapped = np.zeros(T, dtype=bool)
    anchors = sorted(
        ((int(e["seq_frame"]), e["foot"]) for e in step_events),
        key=lambda a: a[0],
    )
    for (t_a, foot_a), (t_b, foot_b) in zip(anchors, anchors[1:]):
        if t_b <= t_a:
            continue
        states = _solve_segment_states(t_a, foot_a, t_b, foot_b)
        for t in range(t_a, t_b + 1):
            if states.get(t, 0):
                result[t, LEG_R] = kp[t, LEG_L]
                result[t, LEG_L] = kp[t, LEG_R]
                swapped[t] = True
            else:
                result[t, LEG_R] = kp[t, LEG_R]
                result[t, LEG_L] = kp[t, LEG_L]

    recon[0, :, :, :2] = result
    _post_dp_fill_leg_gaps(recon, swapped, keypoints_npz_path)
    _post_dp_smooth_and_limit_legs(recon)
    np.savez_compressed(keypoints_npz_path, reconstruction=recon, valid_frames=valid_frames)
    return swapped


def apply_leg_swap_to_foot_keypoints(foot_npz_path, swapped_mask):
    """Apply the same per-frame L/R swap decision from apply_anchor_leg_correction()
    to the COCO-WholeBody foot points (toe/heel), which live outside keypoints.npz
    and are otherwise untouched by the body leg-identity DP correction.

    foot_npz_path: path to foot_keypoints.npz (keypoints order: L_big_toe,
        L_small_toe, L_heel, R_big_toe, R_small_toe, R_heel).
    swapped_mask: per-frame bool array returned by apply_anchor_leg_correction(),
        or None if there weren't enough anchors to run the correction.

    No-ops (does not raise) if foot_npz_path doesn't exist or swapped_mask is None,
    since foot data is optional and the correction may not have run.
    """
    if swapped_mask is None or not os.path.exists(foot_npz_path):
        return

    data = np.load(foot_npz_path, allow_pickle=True)
    keypoints = data["keypoints"].copy()  # (M, T, 6, 2)
    scores = data["scores"].copy()        # (M, T, 6)
    valid_frames = data["valid_frames"]
    keypoint_names = data["keypoint_names"]

    LEFT = [0, 1, 2]
    RIGHT = [3, 4, 5]
    T = keypoints.shape[1]
    for t in range(min(T, len(swapped_mask))):
        if swapped_mask[t]:
            keypoints[:, t, LEFT + RIGHT] = keypoints[:, t, RIGHT + LEFT]
            scores[:, t, LEFT + RIGHT] = scores[:, t, RIGHT + LEFT]

    np.savez_compressed(
        foot_npz_path,
        keypoints=keypoints,
        scores=scores,
        valid_frames=valid_frames,
        keypoint_names=keypoint_names,
    )


def align_foot_keypoints_to_body(foot_npz_path, raw_keypoints_npz_path, keypoints_npz_path, swapped_mask):
    """Re-anchor foot points to the same post-smoothing/post-DP ankle positions
    that the body skeleton in keypoints.npz uses, so the two draw consistently.

    Foot points are never smoothed (see apply_leg_swap_to_foot_keypoints's
    docstring), so a raw foot point can end up tens of pixels from the ankle
    after apply_anchor_leg_correction()'s post-DP leg smoothing/bone-length
    fix moves the ankle -- most visible right after a DP swap, where leg
    smoothing corrects a sudden discontinuity. This does not mean the L/R
    identity is wrong (compare each foot point against the *raw* ankle it was
    actually detected next to, not the smoothed one); it just means the two
    arrays are sitting in different processing stages.

    Fix: express each foot point as an offset from the *raw* ankle it was
    detected next to (using the same swap decision as
    apply_leg_swap_to_foot_keypoints so the correct raw ankle is picked even
    on swapped frames), then re-apply that offset to the *final* smoothed
    ankle position. This keeps the detected toe/heel geometry relative to the
    ankle while letting the point follow wherever smoothing/DP moved the leg.

    Must run after apply_leg_swap_to_foot_keypoints() (foot L/R identity
    already corrected) and after apply_anchor_leg_correction() has returned
    (keypoints_npz_path already holds the final smoothed body).

    No-ops if swapped_mask is None or any required file is missing.
    """
    if swapped_mask is None or not os.path.exists(foot_npz_path):
        return
    if not os.path.exists(raw_keypoints_npz_path) or not os.path.exists(keypoints_npz_path):
        return

    foot_data = np.load(foot_npz_path, allow_pickle=True)
    keypoints = foot_data["keypoints"].copy()  # (M, T, 6, 2), L/R identity already corrected
    scores = foot_data["scores"]
    valid_frames = foot_data["valid_frames"]
    keypoint_names = foot_data["keypoint_names"]

    raw_body = np.load(raw_keypoints_npz_path, allow_pickle=True)["reconstruction"][0]    # (T, 17, 3)
    final_body = np.load(keypoints_npz_path, allow_pickle=True)["reconstruction"][0]      # (T, 17, 3)

    L_ANKLE, R_ANKLE = 6, 3
    LEFT = [0, 1, 2]
    RIGHT = [3, 4, 5]

    T = min(keypoints.shape[1], raw_body.shape[0], final_body.shape[0], len(swapped_mask))
    for t in range(T):
        if swapped_mask[t]:
            raw_l_ankle, raw_r_ankle = raw_body[t, R_ANKLE, :2], raw_body[t, L_ANKLE, :2]
        else:
            raw_l_ankle, raw_r_ankle = raw_body[t, L_ANKLE, :2], raw_body[t, R_ANKLE, :2]
        final_l_ankle = final_body[t, L_ANKLE, :2]
        final_r_ankle = final_body[t, R_ANKLE, :2]

        for fi in LEFT:
            keypoints[:, t, fi] = final_l_ankle + (keypoints[:, t, fi] - raw_l_ankle)
        for fi in RIGHT:
            keypoints[:, t, fi] = final_r_ankle + (keypoints[:, t, fi] - raw_r_ankle)

    np.savez_compressed(
        foot_npz_path,
        keypoints=keypoints,
        scores=scores,
        valid_frames=valid_frames,
        keypoint_names=keypoint_names,
    )


def refresh_step_analysis_after_leg_correction(
    step_analysis,
    config,
    output_dir,
    keypoints_npz,
    offsets_npz,
    meters_per_pixel=None,
):
    """Refresh ankle rows and event coordinates after keypoints were rewritten.

    ``run_step_stride_analysis()`` must run before anchor leg correction because it
    provides the touchdown anchors. After ``apply_anchor_leg_correction()`` rewrites
    left/right leg identity in ``keypoints.npz``, the previously computed
    ``ankle_rows`` still reflect the pre-correction labels. This function keeps the
    already accepted event timing/foot labels, but regenerates ankle rows and event
    coordinates from the corrected keypoints so the final overlay and CSVs use one
    consistent source of truth.
    """
    if not step_analysis:
        return step_analysis

    cameras = config.get("cameras") or []
    if not cameras:
        return step_analysis

    video_path = cameras[0].get("video_path")
    cap = cv2.VideoCapture(video_path) if video_path else None
    fps = cap.get(cv2.CAP_PROP_FPS) if cap and cap.isOpened() else 60.0
    if cap:
        cap.release()
    fps = fps or 60.0

    args = SimpleNamespace(meters_per_pixel=meters_per_pixel)
    ankle_rows = load_ankle_positions(keypoints_npz, offsets_npz, fps)
    rows_by_seq = {int(row["seq_frame"]): row for row in ankle_rows}

    calibrations = {}
    for cam_idx, cam in enumerate(cameras):
        start_line = cam.get("start_line")
        end_line = cam.get("end_line")
        if start_line:
            start_line = [(float(x), float(y)) for x, y in start_line]
        if end_line:
            end_line = [(float(x), float(y)) for x, y in end_line]
        calibrations[cam_idx] = _make_calibration(
            cam,
            config,
            args,
            start_line,
            end_line,
            cam.get("distance_m") or config.get("distance_m"),
        )

    refreshed_events = []
    prev_proj_by_cam = {}
    for event in sorted(step_analysis.get("step_events", []), key=lambda item: int(item["seq_frame"])):
        seq_frame = int(event["seq_frame"])
        row = rows_by_seq.get(seq_frame)
        if row is None:
            refreshed_events.append(event)
            continue

        foot = str(event.get("foot", row["lower_foot"]))
        if foot == "right":
            ankle_x = row["right_ankle_x"]
            ankle_y = row["right_ankle_y"]
            ankle_conf = row["right_ankle_conf"]
        elif foot == "left":
            ankle_x = row["left_ankle_x"]
            ankle_y = row["left_ankle_y"]
            ankle_conf = row["left_ankle_conf"]
        else:
            ankle_x = row["lower_ankle_x"]
            ankle_y = row["lower_ankle_y"]
            ankle_conf = row["lower_ankle_conf"]

        cam_idx = int(row["cam"])
        calibration = calibrations.get(cam_idx) or calibrations.get(0)
        point = (ankle_x, ankle_y)
        track_pos = _project(point, calibration) if calibration else None
        world_x = world_y = None
        if calibration and calibration.get("mode") == "homography":
            world_x, world_y = _transform_homography(point, calibration["homography"])
            step_len_px = None
            prev_proj = prev_proj_by_cam.get(cam_idx)
            step_len_m = None if prev_proj is None else abs(track_pos - prev_proj)
        else:
            prev_proj = prev_proj_by_cam.get(cam_idx)
            step_len_px = None if prev_proj is None or track_pos is None else abs(track_pos - prev_proj)
            mpp = calibration.get("meters_per_pixel") if calibration else None
            step_len_m = None if step_len_px is None or mpp is None else step_len_px * mpp
        if track_pos is not None:
            prev_proj_by_cam[cam_idx] = track_pos

        updated = dict(event)
        updated.update({
            "orig_frame": row["orig_frame"],
            "time_s": row["time_s"],
            "seq_time_s": row["seq_time_s"],
            "cam": row["cam"],
            "ankle_x": ankle_x,
            "ankle_y": ankle_y,
            "ankle_conf": ankle_conf,
            "track_position_px": None if calibration and calibration.get("mode") == "homography" else track_pos,
            "world_x_m": world_x,
            "world_y_m": world_y,
            "step_length_px": step_len_px,
            "step_length_m": step_len_m,
        })
        refreshed_events.append(updated)

    refreshed_events.sort(key=lambda event: int(event["seq_frame"]))
    avg_cadence_spm = add_global_cadence(refreshed_events, ankle_rows)

    step_lengths = [
        float(e["step_length_m"])
        for e in refreshed_events
        if e.get("step_length_m") is not None
    ]
    avg_step_length_m = float(np.mean(step_lengths)) if step_lengths else None

    ankle_csv = step_analysis.get("ankle_csv") or str(Path(output_dir) / "ankle_positions.csv")
    steps_csv = step_analysis.get("steps_csv") or str(Path(output_dir) / "step_events.csv")
    write_csv(ankle_csv, ankle_rows, ANKLE_FIELDS)
    write_csv(steps_csv, refreshed_events, STEP_FIELDS)

    step_analysis["ankle_rows"] = ankle_rows
    step_analysis["step_events"] = refreshed_events
    step_analysis["avg_cadence_spm"] = avg_cadence_spm
    step_analysis["avg_step_length_m"] = avg_step_length_m
    return step_analysis


def write_csv(path, rows, fieldnames):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def _draw_dashed_line(img, pt1, pt2, color, thickness=2, dash_len=12, gap_len=8):
    dx = pt2[0] - pt1[0]
    dy = pt2[1] - pt1[1]
    length = (dx * dx + dy * dy) ** 0.5
    if length == 0:
        return
    ux, uy = dx / length, dy / length
    pos = 0.0
    drawing = True
    while pos < length:
        seg = dash_len if drawing else gap_len
        end_pos = min(pos + seg, length)
        if drawing:
            x1 = int(pt1[0] + ux * pos)
            y1 = int(pt1[1] + uy * pos)
            x2 = int(pt1[0] + ux * end_pos)
            y2 = int(pt1[1] + uy * end_pos)
            cv2.line(img, (x1, y1), (x2, y2), color, thickness)
        pos = end_pos
        drawing = not drawing


def _draw_track_lines(frame, start_line=None, end_line=None):
    if not start_line and not end_line:
        return

    if start_line and end_line:
        p0 = (int(start_line[0][0]), int(start_line[0][1]))
        p3 = (int(start_line[1][0]), int(start_line[1][1]))
        p1 = (int(end_line[0][0]), int(end_line[0][1]))
        p2 = (int(end_line[1][0]), int(end_line[1][1]))
        for a, b in [(p0, p1), (p1, p2), (p2, p3), (p3, p0)]:
            _draw_dashed_line(frame, a, b, (255, 255, 255), thickness=2)
        cv2.line(frame, p0, p3, (0, 0, 0), 5)
        cv2.line(frame, p0, p3, (180, 255, 255), 3)
        cv2.line(frame, p1, p2, (0, 0, 0), 5)
        cv2.line(frame, p1, p2, (255, 200, 100), 3)
    elif start_line:
        p0 = (int(start_line[0][0]), int(start_line[0][1]))
        p1 = (int(start_line[1][0]), int(start_line[1][1]))
        cv2.line(frame, p0, p1, (180, 255, 255), 3)
    elif end_line:
        p0 = (int(end_line[0][0]), int(end_line[0][1]))
        p1 = (int(end_line[1][0]), int(end_line[1][1]))
        cv2.line(frame, p0, p1, (255, 200, 100), 3)


def render_overlay(
    video_path,
    ankle_rows,
    step_events,
    output_video,
    start_line=None,
    end_line=None,
    avg_cadence_spm=None,
):
    if not ankle_rows:
        return

    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        raise FileNotFoundError(f"cannot open video: {video_path}")

    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    fps = cap.get(cv2.CAP_PROP_FPS) or 60.0
    out = cv2.VideoWriter(
        output_video,
        cv2.VideoWriter_fourcc(*"mp4v"),
        fps,
        (width, height),
    )

    events_by_frame = {int(e["orig_frame"]): e for e in step_events}
    event_history = []
    current_pos = 0

    for row in ankle_rows:
        target_frame = int(row["orig_frame"])
        while current_pos <= target_frame:
            ok, frame = cap.read()
            if not ok:
                break
            current_pos += 1

        if not ok:
            break

        _draw_track_lines(frame, start_line=start_line, end_line=end_line)

        rx, ry = int(row["right_ankle_x"]), int(row["right_ankle_y"])
        lx, ly = int(row["left_ankle_x"]), int(row["left_ankle_y"])
        cv2.circle(frame, (rx, ry), 5, (0, 0, 255), -1)
        cv2.circle(frame, (lx, ly), 5, (255, 0, 0), -1)

        event = events_by_frame.get(target_frame)
        if event:
            event_history.append(event)

        for past in event_history[-20:]:
            px, py = int(past["ankle_x"]), int(past["ankle_y"])
            cv2.circle(frame, (px, py), 8, TEXT_COLOR, 2)
            label = f"S{past['step_index']}"
            if past["step_length_m"] is not None:
                label += f" L={past['step_length_m']:.2f}m"
            elif past["step_length_px"] is not None:
                label += f" L={past['step_length_px']:.0f}px"
            label_y = py + 43 if (past['step_index'] % 2 == 1) else py + 70
            cv2.putText(frame, label, (px + 8, label_y),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.55, TEXT_COLOR, 2, cv2.LINE_AA)

        cv2.putText(frame, f"Time: {row['time_s']:.2f}s", (30, 40),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.9, TEXT_COLOR, 2, cv2.LINE_AA)
        cv2.putText(frame, f"Steps: {len(event_history)}", (30, 78),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.9, TEXT_COLOR, 2, cv2.LINE_AA)
        out.write(frame)

    cap.release()
    out.release()


def annotate_step_stride_video(
    input_video,
    output_video,
    ankle_rows,
    step_events,
    avg_cadence_spm=None,
):
    """Draw step length and cadence onto an existing sequential pipeline video."""
    if not ankle_rows:
        return

    cap = cv2.VideoCapture(input_video)
    if not cap.isOpened():
        raise FileNotFoundError(f"cannot open video: {input_video}")

    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    fps = cap.get(cv2.CAP_PROP_FPS) or 60.0
    out = cv2.VideoWriter(
        output_video,
        cv2.VideoWriter_fourcc(*"mp4v"),
        fps,
        (width, height),
    )

    rows_by_seq = {int(r["seq_frame"]): r for r in ankle_rows}
    events_by_seq = {int(e["seq_frame"]): e for e in step_events}
    event_history_by_cam = {}
    frame_idx = 0

    while True:
        ok, frame = cap.read()
        if not ok:
            break

        row = rows_by_seq.get(frame_idx)
        cam_idx = int(row["cam"]) if row else None
        if row:
            rx, ry = int(row["right_ankle_x"]), int(row["right_ankle_y"])
            lx, ly = int(row["left_ankle_x"]), int(row["left_ankle_y"])
            cv2.circle(frame, (rx, ry), 5, (0, 0, 255), -1)
            cv2.circle(frame, (lx, ly), 5, (255, 0, 0), -1)

        event = events_by_seq.get(frame_idx)
        if event:
            event_cam = int(event["cam"])
            event_history_by_cam.setdefault(event_cam, []).append(event)

        cam_history = event_history_by_cam.get(cam_idx, []) if cam_idx is not None else []
        for past in cam_history[-20:]:
            px, py = int(past["ankle_x"]), int(past["ankle_y"])
            cv2.circle(frame, (px, py), 8, TEXT_COLOR, 2)
            label = f"S{past['step_index']}"
            if past["step_length_m"] is not None:
                label += f" L={past['step_length_m']:.2f}m"
            elif past["step_length_px"] is not None:
                label += f" L={past['step_length_px']:.0f}px"
            label_y = py + 43 if (past['step_index'] % 2 == 1) else py + 70
            cv2.putText(frame, label, (px + 8, label_y),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.55, TEXT_COLOR, 2, cv2.LINE_AA)

        if row:
            cv2.putText(frame, f"Time: {row['seq_time_s']:.2f}s", (30, 40),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.9, TEXT_COLOR, 2, cv2.LINE_AA)
        total_steps = sum(len(history) for history in event_history_by_cam.values())
        cv2.putText(frame, f"Steps: {total_steps}", (30, 78),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.9, TEXT_COLOR, 2, cv2.LINE_AA)

        out.write(frame)
        frame_idx += 1

    cap.release()
    out.release()


def run_step_stride_analysis(
    config,
    output_dir=None,
    keypoints_npz=None,
    offsets_npz=None,
    make_video=True,
    output_video=None,
    meters_per_pixel=None,
    min_step_frames=None,
    prominence=None,
):
    """Run ankle, step length, and cadence analysis from a pipeline config dict."""
    cameras = config.get("cameras") or []
    if not cameras:
        raise ValueError("config has no cameras")

    cam_cfg = cameras[0]
    video_path = cam_cfg.get("video_path")
    if not video_path:
        raise ValueError("first camera has no video_path")

    output_dir = output_dir or config.get("output_dir") or str(Path(video_path).resolve().parent)
    stem = Path(video_path).stem
    tracked_stem = f"{stem}_tracked"
    keypoints_npz = keypoints_npz or str(Path(output_dir) / "sequential_tracked" / "input_2D" / "keypoints.npz")
    if not Path(keypoints_npz).exists():
        keypoints_npz = str(Path(output_dir) / tracked_stem / "input_2D" / "keypoints.npz")
    offsets_npz = offsets_npz or str(Path(output_dir) / f"{stem}_offsets.npz")

    if not Path(keypoints_npz).exists():
        raise FileNotFoundError(f"keypoints npz not found: {keypoints_npz}")
    if not Path(offsets_npz).exists():
        raise FileNotFoundError(f"offsets npz not found: {offsets_npz}")

    cap = cv2.VideoCapture(video_path)
    fps = cap.get(cv2.CAP_PROP_FPS) or 60.0
    cap.release()

    args = SimpleNamespace(meters_per_pixel=meters_per_pixel)
    ankle_rows = load_ankle_positions(keypoints_npz, offsets_npz, fps)
    step_events = []

    for cam_idx in sorted({int(row["cam"]) for row in ankle_rows}):
        if cam_idx >= len(cameras):
            continue

        current_cam = cameras[cam_idx]
        start_line = current_cam.get("start_line")
        end_line = current_cam.get("end_line")
        if start_line:
            start_line = [(float(x), float(y)) for x, y in start_line]
        if end_line:
            end_line = [(float(x), float(y)) for x, y in end_line]

        calibration = _make_calibration(
            current_cam,
            config,
            args,
            start_line,
            end_line,
            current_cam.get("distance_m") or config.get("distance_m"),
        )
        cam_rows = [row for row in ankle_rows if int(row["cam"]) == cam_idx]
        cam_events = detect_steps(
            cam_rows,
            calibration,
            fps=fps,
            min_step_frames=min_step_frames,
            prominence=prominence,
        )
        step_events.extend(cam_events)

    step_events.sort(key=lambda event: int(event["seq_frame"]))
    avg_cadence_spm = add_global_cadence(step_events, ankle_rows)

    ankle_csv = str(Path(output_dir) / f"{stem}_ankle_positions.csv")
    steps_csv = str(Path(output_dir) / f"{stem}_step_events.csv")

    write_csv(ankle_csv, ankle_rows, ANKLE_FIELDS)
    write_csv(steps_csv, step_events, STEP_FIELDS)

    overlay_video = None
    if make_video:
        overlay_video = output_video or str(Path(output_dir) / f"{stem}_steps_overlay.mp4")
        render_overlay(
            video_path,
            ankle_rows,
            step_events,
            overlay_video,
            start_line=start_line,
            end_line=end_line,
            avg_cadence_spm=avg_cadence_spm,
        )

    step_lengths = [
        float(e["step_length_m"])
        for e in step_events
        if e.get("step_length_m") is not None
    ]
    avg_step_length_m = float(np.mean(step_lengths)) if step_lengths else None

    return {
        "ankle_csv": ankle_csv,
        "steps_csv": steps_csv,
        "overlay_video": overlay_video,
        "detected_steps": len(step_events),
        "avg_cadence_spm": avg_cadence_spm,
        "avg_step_length_m": avg_step_length_m,
        "ankle_rows": ankle_rows,
        "step_events": step_events,
    }


def parse_args():
    parser = argparse.ArgumentParser(
        description="Extract ankle positions, step events, and step length."
    )
    parser.add_argument("--config", help="pipeline YAML config; used to infer paths")
    parser.add_argument("--video", help="original video path")
    parser.add_argument("--keypoints-npz", help="input_2D/keypoints.npz")
    parser.add_argument("--offsets-npz", help="tracking offsets npz")
    parser.add_argument("--output-dir", help="output directory")
    parser.add_argument("--meters-per-pixel", type=float, default=None)
    parser.add_argument("--distance-m", type=float, default=None)
    parser.add_argument("--start-line", nargs=4, type=float, metavar=("X1", "Y1", "X2", "Y2"))
    parser.add_argument("--end-line", nargs=4, type=float, metavar=("X1", "Y1", "X2", "Y2"))
    parser.add_argument("--min-step-frames", type=int, default=None)
    parser.add_argument("--prominence", type=float, default=None)
    parser.add_argument("--make-video", action="store_true")
    parser.add_argument("--output-video", default=None)
    return parser.parse_args()


def main():
    args = parse_args()
    inferred = {}
    cam_cfg = {}
    cfg = {}
    if args.config:
        inferred = _default_paths_from_config(args.config)
        cfg = inferred["config"]
        cam_cfg = inferred["camera"]

    video_path = args.video or inferred.get("video")
    keypoints_npz = args.keypoints_npz or inferred.get("keypoints_npz")
    offsets_npz = args.offsets_npz or inferred.get("offsets_npz")
    output_dir = args.output_dir or inferred.get("output_dir") or "step_output"

    if not video_path or not keypoints_npz or not offsets_npz:
        raise ValueError("provide --config or all of --video, --keypoints-npz, --offsets-npz")

    cap = cv2.VideoCapture(video_path)
    fps = cap.get(cv2.CAP_PROP_FPS) or 60.0
    cap.release()

    start_line = _parse_line(args.start_line)
    end_line = _parse_line(args.end_line)
    if start_line is None and cam_cfg.get("start_line"):
        start_line = [(float(x), float(y)) for x, y in cam_cfg["start_line"]]
    if end_line is None and cam_cfg.get("end_line"):
        end_line = [(float(x), float(y)) for x, y in cam_cfg["end_line"]]

    distance_m = args.distance_m
    if distance_m is None:
        distance_m = cam_cfg.get("distance_m") or cfg.get("distance_m")

    calibration = _make_calibration(cam_cfg, cfg, args, start_line, end_line, distance_m)

    ankle_rows = load_ankle_positions(keypoints_npz, offsets_npz, fps)
    step_events = detect_steps(
        ankle_rows,
        calibration,
        fps=fps,
        min_step_frames=args.min_step_frames,
        prominence=args.prominence,
    )
    avg_cadence_spm = add_cadence(step_events)

    stem = Path(video_path).stem
    ankle_csv = str(Path(output_dir) / f"{stem}_ankle_positions.csv")
    steps_csv = str(Path(output_dir) / f"{stem}_step_events.csv")

    write_csv(ankle_csv, ankle_rows, ANKLE_FIELDS)
    write_csv(steps_csv, step_events, STEP_FIELDS)

    print(f"Ankle positions: {ankle_csv}")
    print(f"Step events: {steps_csv}")
    print(f"Detected steps: {len(step_events)}")
    if avg_cadence_spm is not None:
        print(f"Average cadence: {avg_cadence_spm:.2f} steps/min")
    if calibration["mode"] == "homography":
        print("Distance calibration: homography world coordinates; step_length_m uses world_x_m difference.")
    elif calibration["meters_per_pixel"] is None:
        print("Distance calibration: none; step_length_m is empty, step_length_px is available.")
    else:
        print(f"Distance calibration: {calibration['meters_per_pixel']:.6f} m/px")

    if args.make_video:
        output_video = args.output_video or str(Path(output_dir) / f"{stem}_steps_overlay.mp4")
        render_overlay(
            video_path,
            ankle_rows,
            step_events,
            output_video,
            start_line=start_line,
            end_line=end_line,
            avg_cadence_spm=avg_cadence_spm,
        )
        print(f"Overlay video: {output_video}")


if __name__ == "__main__":
    main()
