"""
Extract ankle positions, step events, and step length from pipeline 2D keypoints.

This script uses the HRNet/MotionAGFormer 2D keypoints generated by
``run_pipeline.py`` plus the tracking offsets generated in Step 1. It writes:

  - ankle_positions.csv: per-frame left/right ankle positions in original video coordinates
  - step_events.csv: detected foot-strike candidates and step length
  - optional overlay video with ankle/step markers

Distance calibration is optional. If no calibration is provided, step length is
reported in pixels. If homography points, start/end lines plus distance_m, or
--meters-per-pixel are provided, step length is also reported in meters.
"""

from __future__ import annotations

import argparse
import csv
import os
from pathlib import Path
from types import SimpleNamespace

import cv2
import numpy as np
import yaml
from scipy.signal import find_peaks, savgol_filter


RIGHT_ANKLE = 3
LEFT_ANKLE = 6
TEXT_COLOR = (0, 0, 0)



def _parse_line(values):
    if values is None:
        return None
    if len(values) != 4:
        raise ValueError("line must be x1,y1,x2,y2")
    return [(float(values[0]), float(values[1])), (float(values[2]), float(values[3]))]


def _midpoint(line):
    return ((line[0][0] + line[1][0]) / 2.0, (line[0][1] + line[1][1]) / 2.0)


def _track_calibration(start_line, end_line, distance_m, meters_per_pixel):
    if start_line and end_line and distance_m:
        start_mid = _midpoint(start_line)
        end_mid = _midpoint(end_line)
        dx = end_mid[0] - start_mid[0]
        dy = end_mid[1] - start_mid[1]
        span = float((dx * dx + dy * dy) ** 0.5)
        if span <= 0:
            raise ValueError("start_line and end_line have zero distance")
        return {
            "mode": "line",
            "origin": start_mid,
            "direction": (dx / span, dy / span),
            "meters_per_pixel": float(distance_m) / span,
            "homography": None,
        }

    if meters_per_pixel:
        return {
            "mode": "scale",
            "origin": (0.0, 0.0),
            "direction": (1.0, 0.0),
            "meters_per_pixel": float(meters_per_pixel),
            "homography": None,
        }

    return {
        "mode": "pixel",
        "origin": (0.0, 0.0),
        "direction": (1.0, 0.0),
        "meters_per_pixel": None,
        "homography": None,
    }


def _homography_calibration(src_points, dst_points_world):
    if not src_points or not dst_points_world:
        return None

    src = np.asarray(src_points, dtype=np.float32)
    dst = np.asarray(dst_points_world, dtype=np.float32)
    if src.shape != dst.shape or src.ndim != 2 or src.shape[1] != 2:
        raise ValueError("homography_src_points / homography_dst_world must both be shape (N, 2)")
    if len(src) < 4:
        raise ValueError("homography needs at least 4 point pairs")

    H, _ = cv2.findHomography(src, dst, cv2.RANSAC, 5.0)
    if H is None:
        raise ValueError("homography calculation failed")

    return {
        "mode": "homography",
        "origin": (0.0, 0.0),
        "direction": (1.0, 0.0),
        "meters_per_pixel": None,
        "homography": H,
    }


def _make_calibration(cam_cfg, cfg, args, start_line, end_line, distance_m):
    homography = _homography_calibration(
        cam_cfg.get("homography_src_points") or cfg.get("homography_src_points"),
        cam_cfg.get("homography_dst_world") or cfg.get("homography_dst_world"),
    )
    if homography is not None:
        return homography

    return _track_calibration(
        start_line=start_line,
        end_line=end_line,
        distance_m=distance_m,
        meters_per_pixel=args.meters_per_pixel,
    )


def _transform_homography(point, H):
    pts = np.array([[[float(point[0]), float(point[1])]]], dtype=np.float32)
    mapped = cv2.perspectiveTransform(pts, H)
    return float(mapped[0, 0, 0]), float(mapped[0, 0, 1])


def _project(point, calibration):
    if calibration.get("mode") == "homography":
        world_x, _ = _transform_homography(point, calibration["homography"])
        return world_x

    ox, oy = calibration["origin"]
    ux, uy = calibration["direction"]
    return (float(point[0]) - ox) * ux + (float(point[1]) - oy) * uy


def _default_paths_from_config(config_path):
    with open(config_path, "r", encoding="utf-8") as f:
        cfg = yaml.safe_load(f)

    cameras = cfg.get("cameras") or []
    if not cameras:
        raise ValueError("config has no cameras")

    cam = cameras[0]
    video_path = cam.get("video_path")
    if not video_path:
        raise ValueError("first camera has no video_path")

    output_dir = cfg.get("output_dir") or str(Path(video_path).resolve().parent)
    stem = Path(video_path).stem
    tracked_stem = f"{stem}_tracked"

    return {
        "config": cfg,
        "camera": cam,
        "video": video_path,
        "output_dir": output_dir,
        "keypoints_npz": str(Path(output_dir) / tracked_stem / "input_2D" / "keypoints.npz"),
        "offsets_npz": str(Path(output_dir) / f"{stem}_offsets.npz"),
    }


def load_ankle_positions(keypoints_npz, offsets_npz, fps):
    kps_data = np.load(keypoints_npz, allow_pickle=True)
    offsets_data = np.load(offsets_npz, allow_pickle=True)

    keypoints = kps_data["reconstruction"][0]
    valid_frames = np.asarray(kps_data["valid_frames"]).flatten().astype(int)
    offsets = offsets_data["offsets"]
    orig_frames = offsets_data["orig_frames"]
    cam_indices = (
        offsets_data["cam_indices"].astype(int)
        if "cam_indices" in offsets_data
        else np.zeros(len(orig_frames), dtype=int)
    )

    rows = []
    for i, offset_idx in enumerate(valid_frames):
        if offset_idx >= len(offsets) or i >= len(keypoints):
            continue

        frame_kps = keypoints[i]
        off_x, off_y = offsets[offset_idx]
        right = frame_kps[RIGHT_ANKLE]
        left = frame_kps[LEFT_ANKLE]

        right_x, right_y = float(right[0] + off_x), float(right[1] + off_y)
        left_x, left_y = float(left[0] + off_x), float(left[1] + off_y)
        right_conf = float(right[2]) if len(right) > 2 else np.nan
        left_conf = float(left[2]) if len(left) > 2 else np.nan

        if right_y >= left_y:
            lower_foot = "right"
            lower_x, lower_y, lower_conf = right_x, right_y, right_conf
        else:
            lower_foot = "left"
            lower_x, lower_y, lower_conf = left_x, left_y, left_conf

        orig_frame = int(orig_frames[offset_idx])
        rows.append({
            "seq_frame": int(i),
            "offset_index": int(offset_idx),
            "orig_frame": orig_frame,
            "time_s": orig_frame / fps if fps > 0 else i / 60.0,
            "seq_time_s": i / fps if fps > 0 else i / 60.0,
            "cam": int(cam_indices[offset_idx]),
            "right_ankle_x": right_x,
            "right_ankle_y": right_y,
            "right_ankle_conf": right_conf,
            "left_ankle_x": left_x,
            "left_ankle_y": left_y,
            "left_ankle_conf": left_conf,
            "lower_foot": lower_foot,
            "lower_ankle_x": lower_x,
            "lower_ankle_y": lower_y,
            "lower_ankle_conf": lower_conf,
        })
    return rows


def detect_steps(ankle_rows, calibration, fps=None, min_step_frames=None, prominence=None):
    if not ankle_rows:
        return []

    # Estimate FPS from ankle_rows timestamps if not provided.
    if fps is None and len(ankle_rows) >= 2:
        t0 = float(ankle_rows[0]['seq_time_s'])
        t1 = float(ankle_rows[-1]['seq_time_s'])
        n  = len(ankle_rows)
        fps = (n - 1) / (t1 - t0) if t1 > t0 else 30.0
    fps = fps or 30.0

    if min_step_frames is None:
        # Lower-ankle peaks represent every step. Keep the minimum gap fixed so
        # close true contacts are not dropped by find_peaks(distance=...).
        min_step_frames = 5
    min_touchdown_gap_frames = max(8, min_step_frames)

    def smooth(values):
        n = len(values)
        if n < 5:
            return values
        # Keep the lower-ankle smoothing short so close touchdown peaks are not
        # flattened away.
        win = min(7, n if n % 2 == 1 else n - 1)
        if win % 2 == 0:
            win -= 1
        return savgol_filter(values, window_length=win, polyorder=2)

    y = np.array([r["lower_ankle_y"] for r in ankle_rows], dtype=float)
    y_smooth = smooth(y)
    lower_prominence = prominence
    if lower_prominence is None:
        q75, q25 = np.nanpercentile(y_smooth, [75, 25])
        lower_prominence = max((q75 - q25) * 0.20, 1.5)

    peaks, props = find_peaks(
        y_smooth,
        distance=min_step_frames,
        prominence=lower_prominence,
    )
    prominences = props.get("prominences", np.zeros(len(peaks), dtype=float))

    candidates = []
    for peak_idx, peak_prominence in zip(peaks, prominences):
        row = ankle_rows[int(peak_idx)]
        conf = row["lower_ankle_conf"]
        if not (np.isnan(float(conf)) if isinstance(conf, float) else False) and float(conf) < 0.30:
            continue
        candidates.append({
            "row_idx": int(peak_idx),
            "row": row,
            "foot": row["lower_foot"],
            "ankle_x": row["lower_ankle_x"],
            "ankle_y": row["lower_ankle_y"],
            "ankle_conf": conf,
            "prominence": float(peak_prominence),
        })

    filtered_candidates = []
    for candidate in candidates:
        if not filtered_candidates:
            filtered_candidates.append(candidate)
            continue

        previous = filtered_candidates[-1]
        frame_gap = int(candidate["row"]["seq_frame"]) - int(previous["row"]["seq_frame"])
        if frame_gap < min_touchdown_gap_frames:
            prev_score = (previous["prominence"], previous["ankle_conf"], previous["ankle_y"])
            cand_score = (candidate["prominence"], candidate["ankle_conf"], candidate["ankle_y"])
            if cand_score > prev_score:
                filtered_candidates[-1] = candidate
        else:
            filtered_candidates.append(candidate)

    events = []
    prev_proj = None
    for step_idx, candidate in enumerate(filtered_candidates, start=1):
        row = candidate["row"]
        point = (candidate["ankle_x"], candidate["ankle_y"])
        track_pos = _project(point, calibration)
        world_x = world_y = None
        if calibration.get("mode") == "homography":
            world_x, world_y = _transform_homography(point, calibration["homography"])
            step_len_px = None
            step_len_m = None if prev_proj is None else abs(track_pos - prev_proj)
        else:
            step_len_px = None if prev_proj is None else abs(track_pos - prev_proj)
            mpp = calibration["meters_per_pixel"]
            step_len_m = None if step_len_px is None or mpp is None else step_len_px * mpp
        prev_proj = track_pos

        events.append({
            "step_index": step_idx,
            "seq_frame": row["seq_frame"],
            "orig_frame": row["orig_frame"],
            "time_s": row["time_s"],
            "seq_time_s": row["seq_time_s"],
            "cam": row["cam"],
            "foot": candidate["foot"],
            "ankle_x": candidate["ankle_x"],
            "ankle_y": candidate["ankle_y"],
            "ankle_conf": candidate["ankle_conf"],
            "track_position_px": None if calibration.get("mode") == "homography" else track_pos,
            "world_x_m": world_x,
            "world_y_m": world_y,
            "step_length_px": step_len_px,
            "step_length_m": step_len_m,
        })

    return events


def add_cadence(step_events):
    """Add instantaneous and summary cadence in steps per minute."""
    if not step_events:
        return None

    prev_time = None
    intervals = []
    for event in step_events:
        cadence = None
        current_time = float(event["time_s"])
        if prev_time is not None:
            dt = current_time - prev_time
            if dt > 0:
                cadence = 60.0 / dt
                intervals.append(dt)
        event["cadence_spm"] = cadence
        prev_time = current_time

    if len(step_events) >= 2:
        elapsed = float(step_events[-1]["time_s"]) - float(step_events[0]["time_s"])
        if elapsed > 0:
            summary = (len(step_events) - 1) / elapsed * 60.0
        else:
            summary = None
    else:
        summary = None

    for event in step_events:
        event["avg_cadence_spm"] = summary
    return summary


def add_global_cadence(step_events, ankle_rows):
    """Add one full-video average cadence in steps per minute."""
    if not step_events or not ankle_rows:
        return None

    rows_sorted = sorted(ankle_rows, key=lambda row: int(row["seq_frame"]))
    duration = float(rows_sorted[-1]["seq_time_s"]) - float(rows_sorted[0]["seq_time_s"])
    summary = (len(step_events) / duration * 60.0) if duration > 0 else None

    prev_time = None
    for event in sorted(step_events, key=lambda item: int(item["seq_frame"])):
        cadence = None
        current_time = float(event["seq_time_s"])
        if prev_time is not None:
            dt = current_time - prev_time
            if dt > 0:
                cadence = 60.0 / dt
        event["cadence_spm"] = cadence
        event["avg_cadence_spm"] = summary
        prev_time = current_time

    return summary


def write_csv(path, rows, fieldnames):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def _draw_dashed_line(img, pt1, pt2, color, thickness=2, dash_len=12, gap_len=8):
    dx = pt2[0] - pt1[0]
    dy = pt2[1] - pt1[1]
    length = (dx * dx + dy * dy) ** 0.5
    if length == 0:
        return
    ux, uy = dx / length, dy / length
    pos = 0.0
    drawing = True
    while pos < length:
        seg = dash_len if drawing else gap_len
        end_pos = min(pos + seg, length)
        if drawing:
            x1 = int(pt1[0] + ux * pos)
            y1 = int(pt1[1] + uy * pos)
            x2 = int(pt1[0] + ux * end_pos)
            y2 = int(pt1[1] + uy * end_pos)
            cv2.line(img, (x1, y1), (x2, y2), color, thickness)
        pos = end_pos
        drawing = not drawing


def _draw_track_lines(frame, start_line=None, end_line=None):
    if not start_line and not end_line:
        return

    if start_line and end_line:
        p0 = (int(start_line[0][0]), int(start_line[0][1]))
        p3 = (int(start_line[1][0]), int(start_line[1][1]))
        p1 = (int(end_line[0][0]), int(end_line[0][1]))
        p2 = (int(end_line[1][0]), int(end_line[1][1]))
        for a, b in [(p0, p1), (p1, p2), (p2, p3), (p3, p0)]:
            _draw_dashed_line(frame, a, b, (255, 255, 255), thickness=2)
        cv2.line(frame, p0, p3, (0, 0, 0), 5)
        cv2.line(frame, p0, p3, (180, 255, 255), 3)
        cv2.line(frame, p1, p2, (0, 0, 0), 5)
        cv2.line(frame, p1, p2, (255, 200, 100), 3)
    elif start_line:
        p0 = (int(start_line[0][0]), int(start_line[0][1]))
        p1 = (int(start_line[1][0]), int(start_line[1][1]))
        cv2.line(frame, p0, p1, (180, 255, 255), 3)
    elif end_line:
        p0 = (int(end_line[0][0]), int(end_line[0][1]))
        p1 = (int(end_line[1][0]), int(end_line[1][1]))
        cv2.line(frame, p0, p1, (255, 200, 100), 3)


def render_overlay(
    video_path,
    ankle_rows,
    step_events,
    output_video,
    start_line=None,
    end_line=None,
    avg_cadence_spm=None,
):
    if not ankle_rows:
        return

    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        raise FileNotFoundError(f"cannot open video: {video_path}")

    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    fps = cap.get(cv2.CAP_PROP_FPS) or 60.0
    out = cv2.VideoWriter(
        output_video,
        cv2.VideoWriter_fourcc(*"mp4v"),
        fps,
        (width, height),
    )

    events_by_frame = {int(e["orig_frame"]): e for e in step_events}
    event_history = []
    current_pos = 0

    for row in ankle_rows:
        target_frame = int(row["orig_frame"])
        while current_pos <= target_frame:
            ok, frame = cap.read()
            if not ok:
                break
            current_pos += 1

        if not ok:
            break

        _draw_track_lines(frame, start_line=start_line, end_line=end_line)

        rx, ry = int(row["right_ankle_x"]), int(row["right_ankle_y"])
        lx, ly = int(row["left_ankle_x"]), int(row["left_ankle_y"])
        cv2.circle(frame, (rx, ry), 5, (0, 0, 255), -1)
        cv2.circle(frame, (lx, ly), 5, (255, 0, 0), -1)

        event = events_by_frame.get(target_frame)
        if event:
            event_history.append(event)

        for past in event_history[-20:]:
            px, py = int(past["ankle_x"]), int(past["ankle_y"])
            cv2.circle(frame, (px, py), 8, TEXT_COLOR, 2)
            label = f"S{past['step_index']}"
            if past["step_length_m"] is not None:
                label += f" L={past['step_length_m']:.2f}m"
            elif past["step_length_px"] is not None:
                label += f" L={past['step_length_px']:.0f}px"
            label_y = py + 43 if (past['step_index'] % 2 == 1) else py + 70
            cv2.putText(frame, label, (px + 8, label_y),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.55, TEXT_COLOR, 2, cv2.LINE_AA)

        cv2.putText(frame, f"Time: {row['time_s']:.2f}s", (30, 40),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.9, TEXT_COLOR, 2, cv2.LINE_AA)
        cv2.putText(frame, f"Steps: {len(event_history)}", (30, 78),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.9, TEXT_COLOR, 2, cv2.LINE_AA)
        out.write(frame)

    cap.release()
    out.release()


def annotate_step_stride_video(
    input_video,
    output_video,
    ankle_rows,
    step_events,
    avg_cadence_spm=None,
):
    """Draw step length and cadence onto an existing sequential pipeline video."""
    if not ankle_rows:
        return

    cap = cv2.VideoCapture(input_video)
    if not cap.isOpened():
        raise FileNotFoundError(f"cannot open video: {input_video}")

    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    fps = cap.get(cv2.CAP_PROP_FPS) or 60.0
    out = cv2.VideoWriter(
        output_video,
        cv2.VideoWriter_fourcc(*"mp4v"),
        fps,
        (width, height),
    )

    rows_by_seq = {int(r["seq_frame"]): r for r in ankle_rows}
    events_by_seq = {int(e["seq_frame"]): e for e in step_events}
    event_history_by_cam = {}
    frame_idx = 0

    while True:
        ok, frame = cap.read()
        if not ok:
            break

        row = rows_by_seq.get(frame_idx)
        cam_idx = int(row["cam"]) if row else None
        if row:
            rx, ry = int(row["right_ankle_x"]), int(row["right_ankle_y"])
            lx, ly = int(row["left_ankle_x"]), int(row["left_ankle_y"])
            cv2.circle(frame, (rx, ry), 5, (0, 0, 255), -1)
            cv2.circle(frame, (lx, ly), 5, (255, 0, 0), -1)

        event = events_by_seq.get(frame_idx)
        if event:
            event_cam = int(event["cam"])
            event_history_by_cam.setdefault(event_cam, []).append(event)

        cam_history = event_history_by_cam.get(cam_idx, []) if cam_idx is not None else []
        for past in cam_history[-20:]:
            px, py = int(past["ankle_x"]), int(past["ankle_y"])
            cv2.circle(frame, (px, py), 8, TEXT_COLOR, 2)
            label = f"S{past['step_index']}"
            if past["step_length_m"] is not None:
                label += f" L={past['step_length_m']:.2f}m"
            elif past["step_length_px"] is not None:
                label += f" L={past['step_length_px']:.0f}px"
            label_y = py + 43 if (past['step_index'] % 2 == 1) else py + 70
            cv2.putText(frame, label, (px + 8, label_y),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.55, TEXT_COLOR, 2, cv2.LINE_AA)

        if row:
            cv2.putText(frame, f"Time: {row['seq_time_s']:.2f}s", (30, 40),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.9, TEXT_COLOR, 2, cv2.LINE_AA)
        total_steps = sum(len(history) for history in event_history_by_cam.values())
        cv2.putText(frame, f"Steps: {total_steps}", (30, 78),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.9, TEXT_COLOR, 2, cv2.LINE_AA)

        out.write(frame)
        frame_idx += 1

    cap.release()
    out.release()


def run_step_stride_analysis(
    config,
    output_dir=None,
    keypoints_npz=None,
    offsets_npz=None,
    make_video=True,
    output_video=None,
    meters_per_pixel=None,
    min_step_frames=None,
    prominence=None,
):
    """Run ankle, step length, and cadence analysis from a pipeline config dict."""
    cameras = config.get("cameras") or []
    if not cameras:
        raise ValueError("config has no cameras")

    cam_cfg = cameras[0]
    video_path = cam_cfg.get("video_path")
    if not video_path:
        raise ValueError("first camera has no video_path")

    output_dir = output_dir or config.get("output_dir") or str(Path(video_path).resolve().parent)
    stem = Path(video_path).stem
    tracked_stem = f"{stem}_tracked"
    keypoints_npz = keypoints_npz or str(Path(output_dir) / "sequential_tracked" / "input_2D" / "keypoints.npz")
    if not Path(keypoints_npz).exists():
        keypoints_npz = str(Path(output_dir) / tracked_stem / "input_2D" / "keypoints.npz")
    offsets_npz = offsets_npz or str(Path(output_dir) / f"{stem}_offsets.npz")

    if not Path(keypoints_npz).exists():
        raise FileNotFoundError(f"keypoints npz not found: {keypoints_npz}")
    if not Path(offsets_npz).exists():
        raise FileNotFoundError(f"offsets npz not found: {offsets_npz}")

    cap = cv2.VideoCapture(video_path)
    fps = cap.get(cv2.CAP_PROP_FPS) or 60.0
    cap.release()

    args = SimpleNamespace(meters_per_pixel=meters_per_pixel)
    ankle_rows = load_ankle_positions(keypoints_npz, offsets_npz, fps)
    step_events = []

    for cam_idx in sorted({int(row["cam"]) for row in ankle_rows}):
        if cam_idx >= len(cameras):
            continue

        current_cam = cameras[cam_idx]
        start_line = current_cam.get("start_line")
        end_line = current_cam.get("end_line")
        if start_line:
            start_line = [(float(x), float(y)) for x, y in start_line]
        if end_line:
            end_line = [(float(x), float(y)) for x, y in end_line]

        calibration = _make_calibration(
            current_cam,
            config,
            args,
            start_line,
            end_line,
            current_cam.get("distance_m") or config.get("distance_m"),
        )
        cam_rows = [row for row in ankle_rows if int(row["cam"]) == cam_idx]
        cam_events = detect_steps(
            cam_rows,
            calibration,
            fps=fps,
            min_step_frames=min_step_frames,
            prominence=prominence,
        )
        step_events.extend(cam_events)

    step_events.sort(key=lambda event: int(event["seq_frame"]))
    avg_cadence_spm = add_global_cadence(step_events, ankle_rows)

    ankle_csv = str(Path(output_dir) / f"{stem}_ankle_positions.csv")
    steps_csv = str(Path(output_dir) / f"{stem}_step_events.csv")

    ankle_fields = [
        "seq_frame", "offset_index", "orig_frame", "time_s", "seq_time_s", "cam",
        "right_ankle_x", "right_ankle_y", "right_ankle_conf",
        "left_ankle_x", "left_ankle_y", "left_ankle_conf",
        "lower_foot", "lower_ankle_x", "lower_ankle_y", "lower_ankle_conf",
    ]
    step_fields = [
        "step_index", "seq_frame", "orig_frame", "time_s", "seq_time_s", "cam", "foot",
        "ankle_x", "ankle_y", "ankle_conf",
        "track_position_px", "world_x_m", "world_y_m",
        "step_length_px", "step_length_m",
        "cadence_spm", "avg_cadence_spm",
    ]
    write_csv(ankle_csv, ankle_rows, ankle_fields)
    write_csv(steps_csv, step_events, step_fields)

    overlay_video = None
    if make_video:
        overlay_video = output_video or str(Path(output_dir) / f"{stem}_steps_overlay.mp4")
        render_overlay(
            video_path,
            ankle_rows,
            step_events,
            overlay_video,
            start_line=start_line,
            end_line=end_line,
            avg_cadence_spm=avg_cadence_spm,
        )

    step_lengths = [
        float(e["step_length_m"])
        for e in step_events
        if e.get("step_length_m") is not None
    ]
    avg_step_length_m = float(np.mean(step_lengths)) if step_lengths else None

    return {
        "ankle_csv": ankle_csv,
        "steps_csv": steps_csv,
        "overlay_video": overlay_video,
        "detected_steps": len(step_events),
        "avg_cadence_spm": avg_cadence_spm,
        "avg_step_length_m": avg_step_length_m,
        "ankle_rows": ankle_rows,
        "step_events": step_events,
    }


def parse_args():
    parser = argparse.ArgumentParser(
        description="Extract ankle positions, step events, and step length."
    )
    parser.add_argument("--config", help="pipeline YAML config; used to infer paths")
    parser.add_argument("--video", help="original video path")
    parser.add_argument("--keypoints-npz", help="input_2D/keypoints.npz")
    parser.add_argument("--offsets-npz", help="tracking offsets npz")
    parser.add_argument("--output-dir", help="output directory")
    parser.add_argument("--meters-per-pixel", type=float, default=None)
    parser.add_argument("--distance-m", type=float, default=None)
    parser.add_argument("--start-line", nargs=4, type=float, metavar=("X1", "Y1", "X2", "Y2"))
    parser.add_argument("--end-line", nargs=4, type=float, metavar=("X1", "Y1", "X2", "Y2"))
    parser.add_argument("--min-step-frames", type=int, default=None)
    parser.add_argument("--prominence", type=float, default=None)
    parser.add_argument("--make-video", action="store_true")
    parser.add_argument("--output-video", default=None)
    return parser.parse_args()


def main():
    args = parse_args()
    inferred = {}
    cam_cfg = {}
    cfg = {}
    if args.config:
        inferred = _default_paths_from_config(args.config)
        cfg = inferred["config"]
        cam_cfg = inferred["camera"]

    video_path = args.video or inferred.get("video")
    keypoints_npz = args.keypoints_npz or inferred.get("keypoints_npz")
    offsets_npz = args.offsets_npz or inferred.get("offsets_npz")
    output_dir = args.output_dir or inferred.get("output_dir") or "step_output"

    if not video_path or not keypoints_npz or not offsets_npz:
        raise ValueError("provide --config or all of --video, --keypoints-npz, --offsets-npz")

    cap = cv2.VideoCapture(video_path)
    fps = cap.get(cv2.CAP_PROP_FPS) or 60.0
    cap.release()

    start_line = _parse_line(args.start_line)
    end_line = _parse_line(args.end_line)
    if start_line is None and cam_cfg.get("start_line"):
        start_line = [(float(x), float(y)) for x, y in cam_cfg["start_line"]]
    if end_line is None and cam_cfg.get("end_line"):
        end_line = [(float(x), float(y)) for x, y in cam_cfg["end_line"]]

    distance_m = args.distance_m
    if distance_m is None:
        distance_m = cam_cfg.get("distance_m") or cfg.get("distance_m")

    calibration = _make_calibration(cam_cfg, cfg, args, start_line, end_line, distance_m)

    ankle_rows = load_ankle_positions(keypoints_npz, offsets_npz, fps)
    step_events = detect_steps(
        ankle_rows,
        calibration,
        fps=fps,
        min_step_frames=args.min_step_frames,
        prominence=args.prominence,
    )
    avg_cadence_spm = add_cadence(step_events)

    stem = Path(video_path).stem
    ankle_csv = str(Path(output_dir) / f"{stem}_ankle_positions.csv")
    steps_csv = str(Path(output_dir) / f"{stem}_step_events.csv")

    ankle_fields = [
        "seq_frame", "offset_index", "orig_frame", "time_s", "seq_time_s", "cam",
        "right_ankle_x", "right_ankle_y", "right_ankle_conf",
        "left_ankle_x", "left_ankle_y", "left_ankle_conf",
        "lower_foot", "lower_ankle_x", "lower_ankle_y", "lower_ankle_conf",
    ]
    step_fields = [
        "step_index", "seq_frame", "orig_frame", "time_s", "seq_time_s", "cam", "foot",
        "ankle_x", "ankle_y", "ankle_conf",
        "track_position_px", "world_x_m", "world_y_m",
        "step_length_px", "step_length_m",
        "cadence_spm", "avg_cadence_spm",
    ]
    write_csv(ankle_csv, ankle_rows, ankle_fields)
    write_csv(steps_csv, step_events, step_fields)

    print(f"Ankle positions: {ankle_csv}")
    print(f"Step events: {steps_csv}")
    print(f"Detected steps: {len(step_events)}")
    if avg_cadence_spm is not None:
        print(f"Average cadence: {avg_cadence_spm:.2f} steps/min")
    if calibration["mode"] == "homography":
        print("Distance calibration: homography world coordinates; step_length_m uses world_x_m difference.")
    elif calibration["meters_per_pixel"] is None:
        print("Distance calibration: none; step_length_m is empty, step_length_px is available.")
    else:
        print(f"Distance calibration: {calibration['meters_per_pixel']:.6f} m/px")

    if args.make_video:
        output_video = args.output_video or str(Path(output_dir) / f"{stem}_steps_overlay.mp4")
        render_overlay(
            video_path,
            ankle_rows,
            step_events,
            output_video,
            start_line=start_line,
            end_line=end_line,
            avg_cadence_spm=avg_cadence_spm,
        )
        print(f"Overlay video: {output_video}")


if __name__ == "__main__":
    main()